// Sirene's body goes into the altar
IF
Global("C0SireneVampire","GLOBAL",3)
Global("C0SireneBody","AR0809",0)
THEN
RESPONSE #100
ActionOverride("Altar1",CreateItem("c0sbody",0,0,0))
SetGlobal("C0SireneBody","AR0809",1)
END

// Sirene's body

IF
	PartyHasItem("C0SBODY")
	Global("C0SireneBody","AR0809",1)
THEN
  RESPONSE #100
	Wait(2)
	SetGlobal("C0SireneBody","AR0809",2)
	ActionOverride(Player1,StartDialog("player1",Player1))
END